dist: trusty
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  
env:
  - TOMCAT_VERSION=8.5.32

before_script:
  - echo "before_script..."
  - git clone https://github.com/ISID/iPLAss

script:
  - cd iPLAss
  - chmod u+x ./gradlew
  - cd lib/smartgwt
  - wget https://www.smartclient.com/builds/SmartGWT/12.0p/LGPL/latest/smartgwt.jar
  - wget https://www.smartclient.com/builds/SmartGWT/12.0p/LGPL/latest/smartgwt-skins.jar
  - cd ../..
  - ./gradlew build

after_success:
  - echo "success"
