dist: trusty
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
env:
- TOMCAT_VERSION=8.5.32

before_script:
  - echo "before_script..."

install:
- apache-tomcat-$TOMCAT_VERSION/bin/catalina.sh start

script:
  - echo "java -version"
  - ./mvnw -B -Pcheck-duplicate,check-checkstyle,check-cycles,check-cpd,check-pmd,check-findbugs -DskipTests=true install
#  - /usr/bin/xvfb-run ./mvnw -DwebDriverType=firefox verify
#  - /usr/bin/xvfb-run ./mvnw -DwebDriverType=chrome verify
#  - cp -v target/joinfaces-example-*.war  apache-tomcat-$TOMCAT_VERSION/webapps/joinfaces-maven-war-example.war
#  - timeout --preserve-status 60s tail -f apache-tomcat-$TOMCAT_VERSION/logs/catalina.out || true
#  - wget localhost:8080/joinfaces-maven-war-example/index.xhtml

after_success:
  - echo "success"
