dist: trusty
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
cache:
  directories:
  - $HOME/.m2
env:
- TOMCAT_VERSION=8.5.32

before_script:
  - echo "before_script..."
  - git clone https://github.com/ISID/iPLAss

install:
- apache-tomcat-$TOMCAT_VERSION/bin/catalina.sh start

script:
  - cd iPLAss
  - ./gradlew build

after_success:
  - echo "success"
