dist: trusty
language: java
jdk:
  - oraclejdk8
  # - oraclejdk9
  # - oraclejdk10
  # - oraclejdk11
  
env:
  - TOMCAT_VERSION=8.5.32

before_script:
  - echo "before_script..."
  - git clone https://github.com/ISID/iPLAss

script:
  - cd iPLAss
  - chmod u+x ./gradlew
  - ./gradlew build

after_success:
  - echo "success"
