dist: trusty
language: java
jdk:
  # - oraclejdk8
  - openjdk7
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  
env:
  - TOMCAT_VERSION=8.5.32

before_script:
  - echo "before_script..."
  - git clone https://github.com/ISID/iPLAss

script:
  - cd iPLAss
  - cd lib/smartgwt
  - wget https://www.smartclient.com/builds/SmartGWT/12.0p/LGPL/latest/smartgwt.jar
  - wget https://www.smartclient.com/builds/SmartGWT/12.0p/LGPL/latest/smartgwt-skins.jar
  - cd ../..
  # wrapper too old. using the global
  # - curl https://gist.githubusercontent.com/kiminona/19d9feff1f7627845b38f92f404ee499/raw/c8ed8b13df23bac79853c80dd90ef2ac0f3cf295/gradle.properties -O gradle.properties
  # - chmod u+x ./gradlew
  # - ./gradlew --version
  # - ./gradlew wrapper --gradle-version 4.2.1
  - ./gradle --version
  - ./gradle build --stacktrace
  # - gradle build

after_success:
  - echo "success"
