environment:
  global:
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    DOWNLOAD_PATH: C:\Downloads\
    CATALINA_HOME: C:\projects\apache-tomcat-8.0.36
install:
  - java -version
cache:
  - C:\Users\appveyor\.m2
  - C:\Downloads
  
