environment:
  global:
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    DOWNLOAD_PATH: C:\Downloads\
    CATALINA_HOME: C:\projects\apache-tomcat-8.0.36
services:
  - mysql
  - postgresql
build: off
install:
  - java -version
notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
