version: 1.0.SNAPSHOT
environment:
  global:
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    DOWNLOAD_PATH: C:\Downloads\
    CATALINA_HOME: C:\projects\apache-tomcat-8.0.36
install:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
cache:
  - C:\Users\appveyor\.m2
  - C:\Downloads
  
